version: "2"

services:
  guacamole:
    image: guacamole/guacamole:1.3.0
    env_file:
      - ./.guacamole.env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - guacd

  guacd:
    image: guacamole/guacd:1.3.0

  mysql:
    build:
      context: ./
      dockerfile: mysql.Dockerfile
    restart: always
    env_file:
      - ./.mysql.env
    volumes:
      - guacamole-mysql-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  guacamole-mysql-data:
