version: "2"

services:
  guacamole:
    image: guacamole/guacamole:1.4.0
    restart: always
    env_file:
      - ./.guacamole.env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - guacd

  guacd:
    image: guacamole/guacd:1.4.0
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.mysql.env
    volumes:
      - guacamole-mysql-data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/guacamoleinitdb.sql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  guacamole-mysql-data:
